version: "3.9"

services:
  backend:
    build: ./backend
    container_name: agorax-backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - agorax-net
    volumes:
      - ./backend/app:/app/app   # Permite desarrollo en vivo (opcional)
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:17
    container_name: agorax-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agorax-net

  frontend:
    build: ./frontend
    container_name: agorax-frontend
    restart: unless-stopped
    working_dir: /app
    # volumes:
    #   - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - agorax-net
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

volumes:
  postgres_data:

networks:
  agorax-net:
    driver: bridge
